import {
    type Building,
    type NoiseReview,
    type ObjectiveData,
    type CommunityPost,
    type Comment,
    NoiseType,
    TimeSlot,
} from "./types";

export const MOCK_BUILDINGS: Building[] = [
    {
        id: "1",
        address: "서울시 강남구 역삼동 123-45",
        buildingName: "역삼 센트럴 아파트",
        lat: 37.5005,
        lng: 127.0368,
        buildingType: "APARTMENT",
        avgNoiseScore: 3.2,
        predictedNoiseScore: 3.8,
        reviewCount: 32,
        createdAt: "2025-01-15",
        updatedAt: "2026-03-01",
    },
    {
        id: "2",
        address: "서울시 마포구 합정동 456-78",
        buildingName: "합정 리버뷰 오피스텔",
        lat: 37.5495,
        lng: 126.9138,
        buildingType: "OFFICETEL",
        avgNoiseScore: 2.1,
        reviewCount: 18,
        createdAt: "2025-03-20",
        updatedAt: "2026-02-28",
    },
    {
        id: "3",
        address: "서울시 송파구 잠실동 789-12",
        buildingName: "잠실 파크 아파트",
        lat: 37.5133,
        lng: 127.1001,
        buildingType: "APARTMENT",
        avgNoiseScore: 4.1,
        predictedNoiseScore: 4.3,
        reviewCount: 45,
        createdAt: "2025-02-10",
        updatedAt: "2026-03-05",
    },
    {
        id: "4",
        address: "서울시 서초구 반포동 234-56",
        buildingName: "반포 힐스테이트",
        lat: 37.5045,
        lng: 127.0046,
        buildingType: "APARTMENT",
        avgNoiseScore: 1.8,
        reviewCount: 27,
        createdAt: "2025-04-01",
        updatedAt: "2026-02-15",
    },
    {
        id: "5",
        address: "서울시 성동구 성수동 567-89",
        buildingName: "성수 그린 빌라",
        lat: 37.5446,
        lng: 127.0556,
        buildingType: "VILLA",
        avgNoiseScore: 3.6,
        predictedNoiseScore: 3.5,
        reviewCount: 12,
        createdAt: "2025-05-12",
        updatedAt: "2026-03-08",
    },
    {
        id: "6",
        address: "서울시 용산구 이태원동 345-67",
        buildingName: "이태원 스카이 오피스텔",
        lat: 37.5345,
        lng: 126.9946,
        buildingType: "OFFICETEL",
        avgNoiseScore: 4.5,
        predictedNoiseScore: 4.2,
        reviewCount: 8,
        createdAt: "2025-06-01",
        updatedAt: "2026-03-02",
    },
    {
        id: "7",
        address: "서울시 강서구 마곡동 890-12",
        buildingName: "마곡 엠밸리 아파트",
        lat: 37.5665,
        lng: 126.8278,
        buildingType: "APARTMENT",
        avgNoiseScore: 1.5,
        reviewCount: 21,
        createdAt: "2025-07-15",
        updatedAt: "2026-02-20",
    },
    {
        id: "8",
        address: "서울시 노원구 상계동 123-78",
        buildingName: "상계 래미안",
        lat: 37.6548,
        lng: 127.0672,
        buildingType: "APARTMENT",
        avgNoiseScore: 2.8,
        predictedNoiseScore: 3.0,
        reviewCount: 15,
        createdAt: "2025-08-20",
        updatedAt: "2026-03-06",
    },
];

export const MOCK_REVIEWS: NoiseReview[] = [
    {
        id: "r1",
        buildingId: "1",
        nickname: "조용한생활",
        floor: 8,
        noiseScore: 3,
        noiseTypes: [NoiseType.INTER_FLOOR, NoiseType.PET],
        timeOfDay: [TimeSlot.EVENING, TimeSlot.NIGHT],
        description:
            "위층 강아지 소리가 가끔 들립니다. 저녁 시간대에 주로 발생하고, 층간소음도 간간이 있어요. 전체적으로 참을만한 수준입니다.",
        createdAt: "2026-02-15",
        updatedAt: "2026-02-15",
    },
    {
        id: "r2",
        buildingId: "1",
        nickname: "역삼동주민",
        floor: 3,
        noiseScore: 4,
        noiseTypes: [NoiseType.EXTERNAL],
        timeOfDay: [TimeSlot.MORNING, TimeSlot.AFTERNOON],
        description:
            "1층 상가 카페에서 나오는 소음이 심합니다. 특히 주말 오전에 배달 오토바이 소리가 많이 들려요.",
        createdAt: "2026-01-20",
        updatedAt: "2026-01-20",
    },
    {
        id: "r3",
        buildingId: "1",
        nickname: "익명",
        floor: 15,
        noiseScore: 2,
        noiseTypes: [NoiseType.ETC],
        timeOfDay: [TimeSlot.MORNING],
        description:
            "고층이라 외부 소음은 거의 없습니다. 가끔 엘리베이터 소리가 들리는 정도예요.",
        createdAt: "2026-03-01",
        updatedAt: "2026-03-01",
    },
    {
        id: "r4",
        buildingId: "2",
        nickname: "합정러버",
        floor: 5,
        noiseScore: 2,
        noiseTypes: [NoiseType.EXTERNAL],
        timeOfDay: [TimeSlot.EVENING],
        description:
            "합정역 근처라 약간의 소음이 있지만 이중창이라 괜찮습니다. 조용한 편이에요.",
        createdAt: "2026-02-10",
        updatedAt: "2026-02-10",
    },
    {
        id: "r5",
        buildingId: "3",
        nickname: "잠실맘",
        floor: 12,
        noiseScore: 5,
        noiseTypes: [NoiseType.INTER_FLOOR, NoiseType.BABY],
        timeOfDay: [TimeSlot.NIGHT, TimeSlot.MORNING],
        description:
            "위층 아기가 새벽에 울어서 잠을 못 잡니다. 층간소음도 심각한 수준이에요. 이사를 고려 중입니다.",
        createdAt: "2026-02-28",
        updatedAt: "2026-02-28",
    },
    {
        id: "r6",
        buildingId: "3",
        nickname: "송파구민",
        floor: 4,
        noiseScore: 4,
        noiseTypes: [NoiseType.EXTERNAL, NoiseType.TRASH],
        timeOfDay: [TimeSlot.MORNING],
        description:
            "새벽 5시에 쓰레기 수거차 소리가 정말 큽니다. 도로변이라 차량 소음도 계속 들려요.",
        createdAt: "2026-01-15",
        updatedAt: "2026-01-15",
    },
    {
        id: "r7",
        buildingId: "4",
        nickname: "반포조용",
        floor: 20,
        noiseScore: 1,
        noiseTypes: [],
        timeOfDay: [],
        description:
            "정말 조용합니다. 고층이고 단지 내부라 외부 소음이 전혀 없어요. 최고의 주거환경입니다.",
        createdAt: "2026-03-05",
        updatedAt: "2026-03-05",
    },
    {
        id: "r8",
        buildingId: "5",
        nickname: "성수힙",
        floor: 2,
        noiseScore: 4,
        noiseTypes: [NoiseType.EXTERNAL, NoiseType.PET],
        timeOfDay: [TimeSlot.AFTERNOON, TimeSlot.EVENING],
        description:
            "근처 카페 골목이라 오후부터 밤까지 시끄럽습니다. 옆집 강아지도 자주 짖어요.",
        createdAt: "2026-02-20",
        updatedAt: "2026-02-20",
    },
    {
        id: "r9",
        buildingId: "6",
        nickname: "이태원나이트",
        floor: 7,
        noiseScore: 5,
        noiseTypes: [NoiseType.EXTERNAL],
        timeOfDay: [TimeSlot.EVENING, TimeSlot.NIGHT],
        description:
            "주말 밤에는 정말 시끄럽습니다. 클럽과 바 소음이 새벽까지 이어져요. 평일은 그나마 괜찮습니다.",
        createdAt: "2026-01-25",
        updatedAt: "2026-01-25",
    },
    {
        id: "r10",
        buildingId: "7",
        nickname: "마곡직장인",
        floor: 10,
        noiseScore: 1,
        noiseTypes: [],
        timeOfDay: [],
        description:
            "신축이라 방음이 정말 잘 됩니다. 마곡 지역 자체가 조용해서 매우 만족합니다.",
        createdAt: "2026-03-03",
        updatedAt: "2026-03-03",
    },
];

export const MOCK_OBJECTIVE_DATA: Record<string, ObjectiveData> = {
    "1": {
        id: "o1",
        buildingId: "1",
        roadDistance: 30,
        roadLanes: 4,
        nearbyConstruction: true,
        constructionEndDate: "2025-12-31",
        subwayDistance: 150,
        subwayLine: "2호선 역삼역",
        commercialDensity: "HIGH",
        commercialCount: 15,
        updatedAt: "2026-03-01",
    },
    "2": {
        id: "o2",
        buildingId: "2",
        roadDistance: 80,
        roadLanes: 2,
        nearbyConstruction: false,
        subwayDistance: 200,
        subwayLine: "2호선 합정역",
        commercialDensity: "MEDIUM",
        commercialCount: 8,
        updatedAt: "2026-03-01",
    },
    "3": {
        id: "o3",
        buildingId: "3",
        roadDistance: 50,
        roadLanes: 6,
        nearbyConstruction: true,
        constructionEndDate: "2026-06-30",
        subwayDistance: 300,
        subwayLine: "2호선 잠실역",
        commercialDensity: "HIGH",
        commercialCount: 22,
        updatedAt: "2026-03-01",
    },
    "4": {
        id: "o4",
        buildingId: "4",
        roadDistance: 200,
        nearbyConstruction: false,
        subwayDistance: 500,
        subwayLine: "9호선 신반포역",
        commercialDensity: "LOW",
        commercialCount: 3,
        updatedAt: "2026-03-01",
    },
    "5": {
        id: "o5",
        buildingId: "5",
        roadDistance: 20,
        roadLanes: 2,
        nearbyConstruction: true,
        constructionEndDate: "2026-09-30",
        subwayDistance: 400,
        subwayLine: "2호선 성수역",
        commercialDensity: "HIGH",
        commercialCount: 18,
        updatedAt: "2026-03-01",
    },
};

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
    {
        id: "p1",
        userId: "u1",
        nickname: "층간소음고민",
        boardType: "NOISE_HELP",
        region: "서울시 송파구",
        title: "위층 소음 때문에 잠을 못 자요 😭",
        content:
            "잠실 아파트 12층에 사는데 위층에서 밤 11시 이후에도 쿵쿵거리는 소리가 계속 납니다. 관리사무소에 말했는데 개선이 안 되고... 어떻게 해야 할까요? 층간소음 민원 넣어보신 분 계신가요?",
        likeCount: 24,
        commentCount: 8,
        createdAt: "2026-03-08",
        updatedAt: "2026-03-08",
    },
    {
        id: "p2",
        userId: "u2",
        nickname: "마포구이사예정",
        boardType: "QNA",
        region: "서울시 마포구",
        title: "합정동 vs 망원동 어디가 더 조용한가요?",
        content:
            "다음 달에 마포구로 이사 예정인데, 합정동과 망원동 중 어디가 더 조용한지 궁금합니다. 현재 거주하시는 분들 의견 부탁드려요!",
        likeCount: 15,
        commentCount: 12,
        createdAt: "2026-03-07",
        updatedAt: "2026-03-07",
    },
    {
        id: "p3",
        userId: "u3",
        nickname: "방음전문가",
        boardType: "FREE",
        title: "방음 인테리어 후기 공유합니다",
        content:
            "저도 층간소음 때문에 고생하다가 방음 매트 + 방음 커튼 설치했어요. 완벽하진 않지만 체감 50%는 줄어든 것 같습니다. 제가 사용한 제품들 공유할게요.",
        likeCount: 42,
        commentCount: 15,
        createdAt: "2026-03-06",
        updatedAt: "2026-03-06",
    },
    {
        id: "p4",
        userId: "u4",
        nickname: "강남직장인",
        boardType: "QNA",
        region: "서울시 강남구",
        title: "역삼역 근처 오피스텔 추천 부탁드립니다",
        content:
            "역삼역 도보 10분 이내 오피스텔 중에 소음이 적은 곳 추천해주세요. 예산은 보증금 1000/월세 70 정도입니다.",
        likeCount: 8,
        commentCount: 5,
        createdAt: "2026-03-05",
        updatedAt: "2026-03-05",
    },
    {
        id: "p5",
        userId: "u5",
        nickname: "새벽러너",
        boardType: "NOISE_HELP",
        region: "서울시 성동구",
        title: "공사 소음 민원 어디에 넣나요?",
        content:
            "성수동 건물 옆에서 아침 7시부터 공사를 시작하는데 주말에도 합니다. 소음 민원은 어디에 넣어야 하나요? 구청? 경찰?",
        likeCount: 19,
        commentCount: 7,
        createdAt: "2026-03-04",
        updatedAt: "2026-03-04",
    },
];

export const MOCK_COMMENTS: Comment[] = [
    {
        id: "c1",
        postId: "p1",
        userId: "u6",
        nickname: "법률상담",
        content:
            "층간소음 이웃사이센터(1661-2642)에 먼저 상담해보세요. 무료로 중재 서비스를 제공합니다.",
        likeCount: 12,
        createdAt: "2026-03-08",
    },
    {
        id: "c2",
        postId: "p1",
        userId: "u7",
        nickname: "같은아파트",
        content:
            "저도 같은 아파트인데 층간소음 심합니다ㅠㅠ 관리사무소가 별로 적극적이지 않더라고요.",
        likeCount: 5,
        createdAt: "2026-03-08",
    },
    {
        id: "c3",
        postId: "p1",
        userId: "u8",
        nickname: "경험자",
        content:
            "저는 소음 측정 앱으로 기록해둔 후 환경부에 민원 넣었더니 효과 있었어요. 증거가 중요합니다!",
        parentId: "c1",
        likeCount: 8,
        createdAt: "2026-03-09",
    },
    {
        id: "c4",
        postId: "p2",
        userId: "u9",
        nickname: "망원동2년차",
        content:
            "망원동 추천합니다! 합정동보다 유동인구가 적어서 전체적으로 더 조용해요. 다만 망원시장 근처는 피하세요.",
        likeCount: 10,
        createdAt: "2026-03-07",
    },
    {
        id: "c5",
        postId: "p2",
        userId: "u10",
        nickname: "합정거주민",
        content:
            "합정도 골목안쪽은 조용합니다. 대로변만 피하면 살기 좋아요!",
        likeCount: 7,
        createdAt: "2026-03-07",
    },
    {
        id: "c6",
        postId: "p3",
        userId: "u1",
        nickname: "층간소음고민",
        content: "어떤 방음 매트 사용하셨나요? 제품 링크 공유 부탁드려요!",
        likeCount: 3,
        createdAt: "2026-03-06",
    },
];

export const MOCK_SEARCH_SUGGESTIONS = [
    "서울시 강남구 역삼동",
    "서울시 마포구 합정동",
    "서울시 송파구 잠실동",
    "서울시 서초구 반포동",
    "서울시 성동구 성수동",
    "서울시 용산구 이태원동",
    "서울시 강서구 마곡동",
    "서울시 노원구 상계동",
];
